# Generated by Django 4.0.4 on 2022-05-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_operations_exam_alter_operations_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operations',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='description',
            field=models.TextField(blank=True, max_length=70, null=True),
        ),
    ]
