# Generated by Django 4.0.4 on 2022-05-06 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_operations_description_variant_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.variant', verbose_name='variant'),
        ),
    ]
