# Generated by Django 4.0.4 on 2022-05-07 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_operationitem_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.variant', verbose_name='Variant'),
            preserve_default=False,
        ),
    ]
