# Generated by Django 4.0.4 on 2022-05-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_exam_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='finish_date',
            field=models.DateField(verbose_name='Yopilish sanasi'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='start_date',
            field=models.DateField(verbose_name='Ochilish sanasi'),
        ),
    ]
