# Generated by Django 4.0.4 on 2022-05-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_exam_finish_date_alter_exam_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pass_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
