# Generated by Django 4.0.4 on 2022-05-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_exam_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operations',
            name='status',
            field=models.CharField(choices=[('Passed', 'Passed'), ('Fail', 'Fail'), ('not_submit', 'Did not submit')], default='not_submit', max_length=50, verbose_name='Holati'),
        ),
    ]
