# Generated by Django 4.0.4 on 2022-05-18 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_sertificate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sertificate',
        ),
    ]
