# Generated by Django 4.0.4 on 2022-05-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_group_create_at_user_create_at_userpayment_create_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
